# Generated by Django 3.2.5 on 2021-07-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_dateofbirth'),
    ]

    operations = [
    ]
