# Generated by Django 3.2.5 on 2021-07-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
